name: ATOK Headless 24/7 Bot

on:
  workflow_dispatch: # এটি দেওয়ার কারণে আপনি বাটন চেপে ম্যানুয়ালি রান করতে পারবেন
  schedule:
    - cron: '0 */5 * * *' # গিটহাব ৬ ঘণ্টা পর বন্ধ করে দেয়, তাই এটি প্রতি ৫ ঘণ্টা পর পর অটোমেটিক রিস্টার্ট করবে

jobs:
  run-bot:
    runs-on: ubuntu-latest # গিটহাবের লিনাক্স সার্ভার ব্যবহার করবে

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests urllib3

    - name: Run ATOK Bot
      run: |
        python main.py
