name: ATOK 24/7 Auto Bot

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # অ্যাকশনস ট্যাব থেকে ম্যানুয়ালি রান করার জন্য
  schedule:
    - cron: '0 */5 * * *' # গিটহাবের ৬ ঘণ্টার লিমিট এড়াতে প্রতি ৫ ঘণ্টা পর পর অটো রিস্টার্ট হবে

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests urllib3

    - name: Run ATOK Bot
      run: python main.py
